version: '3'

services:
  aiohttp:
    build:
      context: .
      dockerfile: ./docker/aiohtpp/Dockerfile
    image: test
    volumes:
      - .:/app
    env_file:
      - "./docker_env/aiohttp/.local"
      - "./docker_env/postgres/.local"
    ports:
      - "8080:8080"
    command: ["/start_local","db"]
    networks:
      - apinetwork
    depends_on:
      - "db"

  db:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    env_file:
      - "./docker_env/postgres/.local"
    ports:
      - "5432:5432"
    networks:
      - apinetwork

networks:
    apinetwork:
        driver: bridge
