#!/bin/sh

set -o errexit
set -o nounset



until PGPASSWORD=$POSTGRES_PASSWORD psql -h "$1" -U $POSTGRES_USER -d $POSTGRES_DB -c '\q'; do
  >&2 echo "Postgres is unavailable - sleeping"
  sleep 1
done

>&2 echo "Postgres is up - executing command"


python ./livetracker_api/serve.py
